[package]
name = "miden-up"
version = "0.1.0"
edition = "2024"

[dependencies]
miden-lib = { git = "https://github.com/0xPolygonMiden/miden-base", branch = "next", default-features = false }
curl = "0.4.47"
serde = { version = "1.0.219",  features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
clap = { version = "4.5.39", features = ["derive"] }
