[book]
authors = ["Miden contributors"]
description = "Manual for midenup"
language = "en"
multilingual = false
title = "The midenup/miden utility"

[output.html]
git-repository-url = "https://github.com/0xMiden/midenup"

[preprocessor.katex]
after = ["links"]

[preprocessor.alerts]

[output.linkcheck]
exclude = ['[!][A-Z]*']
