name: CI

on:
  push:
    branches: [main, next]
    paths-ignore:
      - "**.md"
      - "**.txt"
      - "manifest/**"
      - "docs/**"
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - "**.md"
      - "**.txt"
      - "manifest/**"
      - "docs/**"

jobs:
  lint:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run clippy
        run: |
          rustup update --no-self-update stable
          rustup component add clippy
          make clippy

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run rustfmt
        run: |
          rustup update --no-self-update nightly
          rustup +nightly component add rustfmt
          make format-check
  build:
    name: build
    # Run this job after the linter, so the cache is hot
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: Swatinem/rust-cache@v2
        with:
          # Only update the cache on push onto the main branch. This strikes a nice balance between
          # cache hits and cache evictions (github has a 10GB cache limit).
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      - name: build
        run: |
          rustup update --no-self-update
          make build

  test:
    name: test
    runs-on: ubuntu-latest
    env:
        SCCACHE_GHA_ENABLED: "true"
        RUSTC_WRAPPER: "sccache"
    steps:
      - uses: mozilla-actions/sccache-action@v0.0.9

      - uses: actions/checkout@main

      - name: Restore Sccache
        id: cache-sccache-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.cache/sccache/
          key: ${{ github.event.pull_request.title }}-sccache

      - uses: taiki-e/install-action@nextest

      - uses: Swatinem/rust-cache@v2
        with:
          # Only update the cache on push onto the main branch. This strikes a nice balance between
          # cache hits and cache evictions (github has a 10GB cache limit).
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - name: install rust
        run: rustup update --no-self-update

      - name: run tests
        run: make test

      - name: Save Sccache
        id: cache-sccache-save
        uses: actions/cache/save@v4
        with:
          path: ~/.cache/sccache/
          key: ${{ github.event.pull_request.title }}-sccache
