name: Use-cases

on:
  push:
    branches: [main, next]
    paths-ignore:
      - "**.md"
      - "**.txt"
      - "manifest/**"
      - "docs/**"
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
    paths-ignore:
      - "**.md"
      - "**.txt"
      - "manifest/**"
      - "docs/**"

jobs:
  build:
    name: build
    # Run this job after the linter, so the cache is hot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: Swatinem/rust-cache@v2
        with:
          # Only update the cache on push onto the main branch. This strikes a nice balance between
          # cache hits and cache evictions (github has a 10GB cache limit).
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      - name: build
        run: |
          rustup update --no-self-update
          make build-release

      - name: Upload resulting executable
        uses: actions/upload-artifact@v4
        with:
          name: midenup_exe
          path: target/release/midenup

  install-stable:
    name: try to install the stable toolchain via the CLI
    needs: [build]
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' || github.event.pull_request.labels.*.name == 'check:install' }}
    steps:
      - uses: actions/checkout@v4
      - name: Download midenup executable
        uses: actions/download-artifact@v4
        with:
          name: midenup_exe
          path: .
      - name: Mark midenup it as executable
        run: |
          chmod +x midenup
      - name: initialize midenup directory
        run: |
          ./midenup init
      - name: install stable
        run: |
          ./midenup install stable
